git:
  depth: false
env:
  global:
  - HUGO_VERSION="0.54.0"
  matrix:
  - secure: mB3yGfhlzHrcTr7y/HWiRYwEe6hcJJYhF8JhtUMSvhFxpt3JU5toEc7EmCt7h+VxwxoyMPR022pCI9OGWI83ZKsSgvRwcZDhSUNk2Zobju6goSmGj6zr7KTxj2QBkTr2iQsu+2Lok4132R4mLqXuee67d0KJOz7NhnU8A9RW5v+q9HnWtryeG0rjf1b6LrvxKcYBFAbefXYkAj43pcPrU1mgvsfXMSXLPfUuI8acDMqj0BSskMnEmACsF1x+WyXIbYZnlFmMrVOy6qpH6h8RU32b2JUYVUfQ5ggUMON0rwncIW93xmJJCyk5zzACvCSpDUsnLUXddgKlAdqGGk2Ij4J6kyg2NE0BjOSH0xFDPnaZq72AMXOTEvIPXZob5gLKcrwmRRsJFQHTVaHfHReXtGqXXCeWsSPNezlb0oGPQ/d+R1/3Usoy7Mx84y4ZmbVekzUyyEq6umB8fNJUvQ8TOLNw3/Cl+2foyRwDzjIUhXS6lCVLh/V/cE1i+ElIWTSJry+Fi5JdIlLvUw6QNFume1Nv8m6l9+lIkydkqWDdh5wu/jVUo+ZMuo/0YUUXwaikwRDIim6cTFDsNnudEMnPzTOYZCe26afg6J9HIOh4LEAZDGdN9+nb7C9gw0HNeWBHNoa+U/iX0kI2HJxoxG9bdxl3CQH+3mEHyGxc/1NbmSQ=
install:
- wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
- tar xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
- mv hugo ~/bin/
script:
- hugo --gc --minify
- echo "$CNAME_URL" > public/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: false
  local_dir: public
  repo: natverse/natverse.github.io
  target_branch: master
  verbose: true
  on:
     branch: dev_pages